DROP TABLE MEMBER_INFO CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE NATIONS CASCADE CONSTRAINTS;
DROP TABLE COMM CASCADE CONSTRAINTS;
DROP TABLE DIVISION CASCADE CONSTRAINTS;
DROP TABLE SPECIAL_INFO CASCADE CONSTRAINTS;
DROP TABLE SLANG CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;


CREATE TABLE MEMBER_INFO (
NO NUMBER NOT NULL,
GRADE_NO VARCHAR2(20) DEFAULT 'GREEN',
ID VARCHAR2(20) NOT NULL,
PWD VARCHAR2(100) NULL,
NICK VARCHAR2(20) NULL,
ENROLL_DATE DATE DEFAULT SYSDATE,
QUIT_YN CHAR(1) DEFAULT 'N',
IS_BLOCKED_YN CHAR(1) DEFAULT 'N',
EMAIL VARCHAR2(200) NULL,
LAST_VISIT DATE NULL,
VISITED_DAYS NUMBER DEFAULT 1,
LOGIN_TYPE NUMBER NULL,
PROFILE VARCHAR2(200) NULL
);
CREATE SEQUENCE SEQ_MEMBER_INFO_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE REVIEW (
	NO NUMBER NOT NULL,
	PRODUCT_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	TITLE VARCHAR2(100) NULL,
	CONTENT VARCHAR2(4000) NULL,
	SCORE NUMBER NULL,
	IS_LIKE NUMBER NULL,
	IS_UNLIKE NUMBER NULL,
	POST_DATE TIMESTAMP NULL,
	SHARE_COUNT NUMBER NULL,
	IS_UPDATE_YN CHAR(1) NULL
);

CREATE TABLE PRODUCT (
	NO NUMBER NOT NULL,
	PRODUCT_COMPANY VARCHAR2(100) NULL,
	PRODUCT_PRICE NUMBER NULL,
	PRODUCT_NAME VARCHAR2(100) NULL,
	CATEGORY_NO NUMBER NOT NULL,
	DELETE_YN CHAR(1) NULL,
	POST_DATE DATE NULL
);

CREATE TABLE ADMIN (
	NO NUMBER NULL,
	ADMIN_ID VARCHAR2(20) NULL,
	ADMIN_PWD NUMBER(20) NULL
);

CREATE TABLE GRADE (
	NO NUMBER NOT NULL,
	GRADE VARCHAR2(10) NULL
);

CREATE TABLE NATIONS (
	NO NUMBER NULL,
	CODE VARCHAR2(4) NULL,
	NAME_KR VARCHAR2(20) NULL,
	NAME_EN VARCHAR2(20) NULL
);

CREATE TABLE COMM (
	NO NUMBER NOT NULL,
	REVIEW_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	POST_DATE TIMESTAMP NULL,
	IS_UPDATE_YN CHAR(1)  DEFAULT 'N'
);

CREATE TABLE DIVISION (
	NO NUMBER NOT NULL,
	CATEGORY_NM VARCHAR2(100) NULL
);

CREATE TABLE SPECIAL_INFO (
	NO NUMBER(20) NOT NULL,
	HEIGHT NUMBER NULL,
	WEIGHT NUMBER NOT NULL,
	NATION_CODE VARCHAR(255) NULL,
	AGE NUMBER NULL
);

CREATE TABLE SLANG (
	NO NUMBER NOT NULL,
	SLANG VARCHAR2(100) NULL
);

CREATE TABLE FAQ (
	NO NUMBER NOT NULL,
	TITLE VARCHAR2(100) NULL,
	CONTENT VARCHAR2(4000) NULL,
	ADMIN_NO NUMBER NOT NULL,
	DELETE_YN CHAR(1) NULL DEFAULT 'N'
);
CREATE SEQUENCE SEQ_FAQ_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE QNA (
	NO NUMBER NOT NULL,
	TITLE VARCHAR2(100) NULL,
	CONTENT VARCHAR2(4000) NULL,
	ANSWER VARCHAR2(4000) NULL,
	MEMBER_NO NUMBER NOT NULL,
	ADMIN_NO NUMBER NULL,
    COUNT NUMBER DEFAULT 0,
	Q_DATE TIMESTAMP NULL,
	A_DATE TIMESTAMP NULL,
	DELETE_YN CHAR(1) DEFAULT 'N',
	EDIT_DATE TIMESTAMP NULL
);
CREATE SEQUENCE SEQ_QNA_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE INQUIRY_TYPE
(NO NUMBER NOT NULL,
TYPE VARCHAR2(100) NOT NULL);
CREATE SEQUENCE SEQ_INQUIRY_TYPE_NO START WITH 1 INCREMENT BY 1;

CREATE TABLE ATTACHMENT (
	NO NUMBER NOT NULL,
	ATT_URL VARCHAR2(1000) NULL,
	REVIEW_NO NUMBER NOT NULL
);

ALTER TABLE MEMBER_INFO ADD CONSTRAINT PK_MEMBER_INFO PRIMARY KEY (NO);
ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (NO);
ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (NO);
ALTER TABLE ADMIN ADD CONSTRAINT PK_ADMIN PRIMARY KEY (NO);
ALTER TABLE GRADE ADD CONSTRAINT PK_GRADE PRIMARY KEY (NO);
ALTER TABLE NATIONS ADD CONSTRAINT PK_NATIONS PRIMARY KEY (NO);
ALTER TABLE COMM ADD CONSTRAINT PK_COMM PRIMARY KEY (NO);
ALTER TABLE DIVISION ADD CONSTRAINT PK_DIVISION PRIMARY KEY (NO);
ALTER TABLE SPECIAL_INFO ADD CONSTRAINT PK_SPECIAL_INFO PRIMARY KEY (NO);
ALTER TABLE SLANG ADD CONSTRAINT PK_SLANG PRIMARY KEY (NO);
ALTER TABLE FAQ ADD CONSTRAINT PK_FAQ PRIMARY KEY (NO);
ALTER TABLE QNA ADD CONSTRAINT PK_QNA PRIMARY KEY (NO);
ALTER TABLE INQUIRY_TYPE ADD CONSTRAINT PK_INQUIRY_TYPE PRIMARY KEY (NO);
ALTER TABLE ATTACHMENT ADD CONSTRAINT PK_ATTACHMENT PRIMARY KEY (NO);
ALTER TABLE SPECIAL_INFO ADD CONSTRAINT FK_MEMBER_INFO FOREIGN KEY (NO)
REFERENCES MEMBER_INFO (NO);

INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(1, '어떻게 리뷰를 작성하나요?', '리뷰 작성 방법은 로그인 후 해당 제품 페이지로 이동하셔서 별점과 함께 사용 후기를 작성하시면 됩니다.', 1004, 'N');

INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(2, '리뷰를 수정하거나 삭제하려면 어떻게 해야 하나요?', '마이페이지에서 작성한 리뷰 목록을 확인하실 수 있습니다. 원하는 리뷰를 선택하여 수정 또는 삭제할 수 있습니다.', 1004, 'N');

INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(3, '다른 사용자의 리뷰를 신뢰할 수 있을까요?', '리뷰는 다양한 사용자의 의견을 담고 있어서 유용한 정보를 제공할 수 있습니다. 하지만 개인의 경험에 따라 리뷰가 다를 수 있기 때문에 여러 리뷰를 종합적으로 고려하면 좋습니다.', 1004, 'N');

INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(4, '리뷰 작성 시 보상을 받을 수 있나요?', '일부 사이트에서는 리뷰 작성 시 포인트나 할인 쿠폰 등의 보상을 제공할 수 있습니다. 하지만 중요한 것은 솔직한 리뷰를 작성하는 것이며, 보상을 위해 부정확하거나 허위의 내용을 작성하는 것은 바람직하지 않습니다.', 1004, 'N');
INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(5, '로그인이 안 되는데 어떻게 해야 하나요?', '먼저 아이디와 비밀번호를 정확하게 입력했는지 확인해주세요. 또한, Caps Lock 키가 켜져 있는지, 브라우저 캐시를 비워보는 것도 도움이 될 수 있습니다. 계정이 정상적으로 활성화되었는지 확인해보세요.', 1004, 'N');

INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(6, '비밀번호를 잊어버렸는데 어떻게 하면 비밀번호를 재설정할 수 있나요?', '로그인 페이지에서 ''비밀번호 재설정'' 또는 ''비밀번호 찾기'' 옵션을 클릭하세요. 등록된 이메일로 비밀번호 재설정 링크가 전송됩니다. 링크를 통해 새 비밀번호를 설정할 수 있습니다.', 1004, 'N');

DELETE FROM FAQ WHERE NO = 6;
INSERT INTO FAQ (NO, TITLE, CONTENT, ADMIN_NO, DELETE_YN) VALUES
(7, '회원가입 시에 오류가 발생하고 있는데 어떤 문제일까요?', '회원가입 시에 필수 정보를 모두 올바르게 입력했는지 확인해주세요. 아이디, 이메일 등이 이미 다른 사용자에게 사용 중인지 확인하고, 입력 양식을 정확하게 따랐는지도 확인해보세요. 또한, 회원가입 중에 나타난 오류 메시지를 읽어보며 문제를 파악할 수도 있습니다.', 1004, 'N');

INSERT INTO QNA
(NO, 
TITLE, 
CONTENT, 
ANSWER, 
MEMBER_NO, 
ADMIN_NO, 
Q_DATE, 
A_DATE,
DELETE_YN
)
VALUES
(1,
'회원등급이 올라가지 않아요',
'안녕하세요 운영자님, 제가 알고있는 등급 규정에 충족한 것으로 알고있는데 등급이 안올라요 왜예여?',
'안녕하십니까 고객님, 현재 출석일 수는 충족되었으나 리뷰 작성 개수가 부족하신것으로 확인됩니다. 감사합니다.',
62,
1004,
SYSTIMESTAMP, 
TO_TIMESTAMP('2023-08-17 13:20:00', 'YYYY-MM-DD HH24:MI:SS'),
'N'
);

INSERT INTO INQUIRY_TYPE
(
NO,
TYPE
)
VALUES
(SEQ_INQUIRY_TYPE_NO.NEXTVAL,
'계정문의'
);
INSERT INTO INQUIRY_TYPE
(
NO,
TYPE
)
VALUES
(SEQ_INQUIRY_TYPE_NO.NEXTVAL,
'신고문의'
);
INSERT INTO INQUIRY_TYPE
(
NO,
TYPE
)
VALUES
(SEQ_INQUIRY_TYPE_NO.NEXTVAL,
'리뷰작성문의'
);
INSERT INTO INQUIRY_TYPE
(
NO,
TYPE
)
VALUES
(SEQ_INQUIRY_TYPE_NO.NEXTVAL,
'건의사항'
);
select * from INQUIRY_TYPE;
COMMIT;